#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config window_gap           20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xrandr --output HDMI-0 --mode 3840x2160 --rate 60 --primary
xrandr --output DVI-D-0 --mode 1920x1080 --left-of HDMI-0 --scale 1
sleep 5

setxkbmap -option caps:escape
picom --xrender-sync-fence &
flameshot &
redshift &
xsetroot -cursor_name left_ptr &
xrdb ~/.Xresources
dunst &
xmousepasteblock &
ntfd &
udiskie &
bluetoothctl power on &
wmname compiz

bspc monitor HDMI-0   -d 1 2 3 4 5 6 7 8
bspc monitor DVI-D-0  -d 9 10
bspc config focused_border_color $color5
bspc config normal_border_color $background
bspc config top_padding 40

xautolock -time 5 -locker "~/Scripts/locker.sh" -corners ---- &

polybar main -r &
feh --bg-scale $HOME/Wallpapers/leaves.jpg &
